include "base"
include "version"
include required(file("/opt/lila/runtime/secrets.conf"))

http.address = "0.0.0.0"
http.port = 9663

net.site.name = "Lila for Vortex"
net.domain = ${?LILA_DOMAIN}
net.socket.domains = [${?LILA_SOCKET_DOMAIN}]
net.socket.alts = []
net.asset.domain = ${?LILA_DOMAIN}
net.asset.base_url = ${?LILA_URL}
net.base_url = ${?LILA_URL}
net.crawlable = false
net.ratelimit = ${?ENABLE_RATE_LIMITING}
net.http.log = false

mongodb.uri = ${?LILA_MONGODB_URI}
redis.uri = ${?LILA_REDIS_URI}

search.enabled = false
mailer.primary.mock = true
mailer.secondary.mock = true
security.email_confirm.enabled = false
turnstile.enabled = false
kamon.enabled = false
fishnet.offline_mode = true
